### ISSUE TITLE
Support AE2 UEL:Extended

### ISSUE THREAD

**Issue by mczph** [NotMyWing/NAE2#12] opened 2023-10-04 10:41 UTC
![image](https://github.com/NotMyWing/NAE2/assets/103164772/b0aa1c4a-bb6f-4ad2-bb93-934e7d060426)

Modlist:
![image](https://github.com/NotMyWing/NAE2/assets/103164772/3b677b13-f41b-4bc7-86c4-e83291236a0f)

https://github.com/beecupbe/ae2uel_extended/issues/15

**Comment by NotMyWing** [comment] 2023-10-06 07:02
Duplicate of #6.

**Closed** 2023-10-06 07:02 UTC
